---
- name: Converge
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: mariadb.mariadb.com/mariadb-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/mariadb_v1alpha1_mariadb_cr.yaml'])) | from_yaml }}"

  tasks:
    - name: Create the mariadb.mariadb.com/v1alpha1.MariaDB
      k8s:
        namespace: '{{ namespace }}'
        definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/mariadb_v1alpha1_mariadb_cr.yaml'])) }}"

    - name: Get the newly created Custom Resource
      debug:
        msg: "{{ lookup('k8s',
          group='mariadb.mariadb.com',
          api_version='v1alpha1',
          kind='MariaDB',
          namespace=namespace,
          resource_name=custom_resource.metadata.name
        )}}"

    - name: Wait 60s for reconciliation to run
      k8s_info:
        api_version: 'v1alpha1'
        kind: 'MariaDB'
        namespace: '{{ namespace }}'
        name: '{{ custom_resource.metadata.name }}'
      register: reconcile_cr
      until:
        - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
      delay: 6
      retries: 10

- import_playbook: '{{ playbook_dir }}/../default/asserts.yml'
